using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Medical.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class ConfigurableCyberEyesWindow : DefaultWindow
{
    public event Action<Color>? OnSave;

    public ConfigurableCyberEyesWindow()
    {
        RobustXamlLoader.Load(this);
        IrisColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        IrisColorSelector.IsAlphaVisible = false;
        SaveButton.OnPressed += _ => OnSave?.Invoke(IrisColorSelector.Color);
    }

    public void SetColor(Color color)
    {
        IrisColorSelector.Color = color;
    }
}
